version: '3'
services: 
  nginx: 
    restart: always
    build: 
      dockerfile: Dockerfile.dev 
      context: ./nginx
    ports: 
      - '3050:80'
  postgres: 
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  registrybackend: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./RegistryBackend 
    environment: 
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  frontend: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - /app/node_modules 
      - ./frontend:/app