FROM ubuntu:latest
EXPOSE 8080

RUN sudo apt-get install openjdk-8-jdk
RUN curl -s "https://get.sdkman.io" | bash
RUN sdk install gradle 7.5.1

COPY . . 

RUN gradle clean 
RUN gradle fatJar

ENTRYPOINT ["java", "-jar", "dockerapp.jar"]

#RegistryBackend-0.0.1-SNAPSHOT.jar